# docker-compose.yml
version: '3'

services:

  backend:
     restart: always
     tty: true
     image: andresvidal/rpi3-mongodb3
     ports:
       - "27017:27017"
     env_file:
       - ./mongo/user_setup_vars.env
     # repair db on restart && relauch in repaired state...
     command: bash -c 'mongod --repair && mongod'
   
  master_node:
    build: ./
    tty: true
    volumes:
      - "/mediaES:/rss_library"
      - "./proj:/proj"
    env_file:
      - ./mongo/user_setup_vars.env
    depends_on:
      - backend
    links:
      - "backend:rss_backend_1"
              
