# docker-compose.yml
version: '3'

services:

  backend:
    restart: always
    image: 'mongo'
    ports:
      - "27017:27017"
    env_file:
      - ./mongo/user_setup_vars.env
      
  master_node:
    build: ./
    tty: true
    volumes:
      - "workerdata:/proj/data"
      - "./proj:/proj"
    command:  # Comment out to debug && start beat in container...
      ['celery', '-A', 'proj', 'beat', '-s' , '/celerybeat-schedule',  '--app=proj.celery_cfg', '-Q=downloads,default']
    env_file:
      - ./mongo/user_setup_vars.env
    depends_on:
      - backend
    links:
      - "backend"
          
volumes:
  workerdata:
